"""Curated offline-safe fallbacks for the registry proxies.

The Skills and Plugins tabs must always render something useful — even
if ClawHub is down, GitHub's API rate-limits us, or the user is offline.
The lists here are hand-curated, intentionally conservative, and short
enough to maintain by hand.

To update:
    - Add an entry with all fields populated.
    - For unverified items (not Anthropic / not a trusted publisher),
      set verified=False so the UI surfaces the warning per the
      Feb 2026 ClawHub incident.
    - Keep tags lowercase and single-word where possible.
    - stars / downloads / installs are approximate — they help sorting
      but don't need to be exact.
"""
from __future__ import annotations


def _skill(
    sid: str, *, name: str, description: str, source: str, source_label: str,
    url: str, tags: list[str], stars: int | None = None,
    downloads: int | None = None, verified: bool = False,
    author: str | None = None,
) -> dict:
    return {
        "id": sid, "name": name, "description": description,
        "source": source, "source_label": source_label,
        "url": url, "tags": tags, "stars": stars,
        "downloads": downloads, "verified": verified, "author": author,
    }


def _mcp(
    sid: str, *, name: str, description: str, source: str, source_label: str,
    install: dict, category: str, permissions: list[str],
    homepage: str | None = None, verified: bool = False,
    installs: int | None = None,
) -> dict:
    return {
        "id": sid, "name": name, "description": description,
        "source": source, "source_label": source_label,
        "install": install, "category": category, "permissions": permissions,
        "homepage": homepage, "verified": verified, "installs": installs,
    }


CURATED_SKILLS: list[dict] = [
    # ── Anthropic Cookbook ────────────────────────────────────────────────
    _skill("cookbook/agentic-search", name="agentic-search",
        description="Iterative web search loop with citation tracking and source ranking.",
        source="cookbook", source_label="Anthropic Cookbook",
        url="https://github.com/anthropics/anthropic-cookbook/tree/main/skills/agentic-search",
        tags=["research", "search"], verified=True, author="anthropic"),
    _skill("cookbook/code-review", name="code-review",
        description="Structured code review with bug categories and severity scoring.",
        source="cookbook", source_label="Anthropic Cookbook",
        url="https://github.com/anthropics/anthropic-cookbook/tree/main/skills/code-review",
        tags=["code", "review"], verified=True, author="anthropic"),
    _skill("cookbook/sql-explainer", name="sql-explainer",
        description="Walks SQL queries in natural language with EXPLAIN context.",
        source="cookbook", source_label="Anthropic Cookbook",
        url="https://github.com/anthropics/anthropic-cookbook/tree/main/skills/sql-explainer",
        tags=["sql", "data"], verified=True, author="anthropic"),
    _skill("cookbook/refactor", name="refactor",
        description="Pattern-driven refactoring with safety checks and test preservation.",
        source="cookbook", source_label="Anthropic Cookbook",
        url="https://github.com/anthropics/anthropic-cookbook/tree/main/skills/refactor",
        tags=["code", "refactor"], verified=True, author="anthropic"),
    _skill("cookbook/structured-extract", name="structured-extract",
        description="Extract structured fields from messy text with confidence scores.",
        source="cookbook", source_label="Anthropic Cookbook",
        url="https://github.com/anthropics/anthropic-cookbook/tree/main/skills/structured-extract",
        tags=["nlp", "extract"], verified=True, author="anthropic"),
    _skill("cookbook/doc-rag", name="doc-rag",
        description="Retrieval-augmented doc Q&A — chunk, embed, retrieve, cite.",
        source="cookbook", source_label="Anthropic Cookbook",
        url="https://github.com/anthropics/anthropic-cookbook/tree/main/skills/doc-rag",
        tags=["rag", "ai"], verified=True, author="anthropic"),
    _skill("cookbook/orchestrator-coordinator", name="orchestrator-coordinator",
        description="Multi-agent coordination patterns: handoff, reduce, vote.",
        source="cookbook", source_label="Anthropic Cookbook",
        url="https://github.com/anthropics/anthropic-cookbook/tree/main/skills/orchestrator-coordinator",
        tags=["agents", "orchestration"], verified=True, author="anthropic"),
    _skill("cookbook/test-generation", name="test-generation",
        description="Generate unit tests from code with edge cases and fixtures.",
        source="cookbook", source_label="Anthropic Cookbook",
        url="https://github.com/anthropics/anthropic-cookbook/tree/main/skills/test-generation",
        tags=["testing", "code"], verified=True, author="anthropic"),

    # ── ClawHub — Python ──────────────────────────────────────────────────
    _skill("clawhub/python-testing", name="python-testing",
        description="Pytest patterns with fixtures, parametrize, mocks, and coverage targets.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/python-testing",
        tags=["python", "testing", "pytest"], stars=1240, downloads=8400, verified=True),
    _skill("clawhub/fastapi-patterns", name="fastapi-patterns",
        description="Dependency injection, Pydantic models, async lifespans, OpenAPI idioms.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/fastapi-patterns",
        tags=["python", "fastapi", "backend"], stars=690, downloads=3800, verified=True),
    _skill("clawhub/django-rest", name="django-rest",
        description="Django REST framework: serializers, viewsets, permissions, throttling.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/django-rest",
        tags=["python", "django", "backend"], stars=510, downloads=2900, verified=True),
    _skill("clawhub/flask-modern", name="flask-modern",
        description="Modern Flask with blueprints, app factory, async views, and type hints.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/flask-modern",
        tags=["python", "flask", "backend"], stars=320, downloads=1700, verified=True),
    _skill("clawhub/async-python", name="async-python",
        description="asyncio patterns: gather, semaphores, TaskGroup, structured concurrency.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/async-python",
        tags=["python", "async"], stars=860, downloads=4400, verified=True),
    _skill("clawhub/pandas-recipes", name="pandas-recipes",
        description="Idiomatic pandas: groupby, merge, missing data, performance.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/pandas-recipes",
        tags=["python", "data", "pandas"], stars=1090, downloads=6200, verified=True),
    _skill("clawhub/polars-modern", name="polars-modern",
        description="Polars idioms: lazy frames, expressions, joins, streaming.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/polars-modern",
        tags=["python", "data", "polars"], stars=470, downloads=2100, verified=True),

    # ── ClawHub — Frontend ────────────────────────────────────────────────
    _skill("clawhub/react-hooks", name="react-hooks",
        description="Idiomatic React hooks patterns and common pitfalls.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/react-hooks",
        tags=["react", "frontend", "javascript"], stars=980, downloads=5600, verified=True),
    _skill("clawhub/nextjs-app-router", name="nextjs-app-router",
        description="Next.js App Router: layouts, server actions, streaming, caching.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/nextjs-app-router",
        tags=["nextjs", "react", "frontend"], stars=820, downloads=4100, verified=True),
    _skill("clawhub/vue-composition", name="vue-composition",
        description="Vue 3 Composition API: composables, provide/inject, suspense.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/vue-composition",
        tags=["vue", "frontend"], stars=410, downloads=1800, verified=True),
    _skill("clawhub/svelte-runes", name="svelte-runes",
        description="Svelte 5 runes ($state, $derived, $effect) and SvelteKit patterns.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/svelte-runes",
        tags=["svelte", "frontend"], stars=290, downloads=1100, verified=True),
    _skill("clawhub/typescript-strict", name="typescript-strict",
        description="TypeScript strict-mode idioms: no `any`, narrowed unions, branded types.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/typescript-strict",
        tags=["typescript", "strict"], stars=760, downloads=4100, verified=True),
    _skill("clawhub/tailwind-system", name="tailwind-system",
        description="Designing with Tailwind: tokens, dark mode, responsive scaling.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/tailwind-system",
        tags=["css", "tailwind", "design"], stars=620, downloads=3100, verified=True),
    _skill("clawhub/css-modern", name="css-modern",
        description="Modern CSS: container queries, :has(), cascade layers, color-mix.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/css-modern",
        tags=["css", "frontend"], stars=380, downloads=1500, verified=True),
    _skill("clawhub/accessibility-a11y", name="accessibility-a11y",
        description="WCAG patterns, ARIA roles, focus management, keyboard nav.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/accessibility-a11y",
        tags=["accessibility", "frontend"], stars=540, downloads=2400, verified=True),

    # ── ClawHub — Node / JS backend ───────────────────────────────────────
    _skill("clawhub/express-modern", name="express-modern",
        description="Express with async/await, error middleware, validation, type hints.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/express-modern",
        tags=["node", "javascript", "backend"], stars=540, downloads=2700, verified=True),
    _skill("clawhub/nestjs-patterns", name="nestjs-patterns",
        description="NestJS modules, DI, guards, pipes, exception filters.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/nestjs-patterns",
        tags=["node", "nestjs", "backend"], stars=380, downloads=1700, verified=True),
    _skill("clawhub/prisma-idioms", name="prisma-idioms",
        description="Prisma schema design, migrations, transactions, performance.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/prisma-idioms",
        tags=["node", "prisma", "orm"], stars=450, downloads=2000, verified=True),
    _skill("clawhub/zod-validation", name="zod-validation",
        description="Zod schemas: parsing, refinements, branded types, error formatting.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/zod-validation",
        tags=["node", "typescript", "validation"], stars=590, downloads=3000, verified=True),

    # ── ClawHub — Data / SQL ──────────────────────────────────────────────
    _skill("clawhub/sql-schema-design", name="sql-schema-design",
        description="Designing normalised schemas with indexes, constraints, migrations.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/sql-schema-design",
        tags=["sql", "data"], stars=540, downloads=2900, verified=True),
    _skill("clawhub/postgres-tuning", name="postgres-tuning",
        description="Postgres performance: EXPLAIN, indexes, vacuum, work_mem, pools.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/postgres-tuning",
        tags=["sql", "postgres", "performance"], stars=480, downloads=2200, verified=True),
    _skill("clawhub/sqlalchemy-modern", name="sqlalchemy-modern",
        description="SQLAlchemy 2.0 ORM: typed sessions, async, mapped dataclasses.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/sqlalchemy-modern",
        tags=["python", "sql", "orm"], stars=510, downloads=2600, verified=True),
    _skill("clawhub/duckdb-analytics", name="duckdb-analytics",
        description="DuckDB for in-process analytics: CSV, parquet, joins, partitions.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/duckdb-analytics",
        tags=["sql", "duckdb", "data"], stars=290, downloads=900, verified=True),

    # ── ClawHub — DevOps ──────────────────────────────────────────────────
    _skill("clawhub/docker-multi-stage", name="docker-multi-stage",
        description="Multi-stage Dockerfiles for Python / Node / Go with small final images.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/docker-multi-stage",
        tags=["docker", "devops"], stars=820, downloads=4400, verified=True),
    _skill("clawhub/k8s-manifests", name="k8s-manifests",
        description="Kubernetes manifests: Deployment, Service, Ingress, HPA, probes.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/k8s-manifests",
        tags=["kubernetes", "devops"], stars=720, downloads=3500, verified=True),
    _skill("clawhub/terraform-aws", name="terraform-aws",
        description="Terraform on AWS: modules, state, drift, S3/RDS/ECS.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/terraform-aws",
        tags=["terraform", "aws", "devops"], stars=610, downloads=2900, verified=True),
    _skill("clawhub/github-actions", name="github-actions",
        description="GitHub Actions workflows: matrix, caching, reusable jobs.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/github-actions",
        tags=["ci", "devops", "github"], stars=540, downloads=2700, verified=True),
    _skill("clawhub/nginx-config", name="nginx-config",
        description="Production nginx: upstreams, gzip, TLS, security headers, rate limiting.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/nginx-config",
        tags=["nginx", "devops"], stars=340, downloads=1400, verified=True),
    _skill("clawhub/observability-otel", name="observability-otel",
        description="OpenTelemetry: traces, metrics, logs, sampling, exporters.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/observability-otel",
        tags=["observability", "devops"], stars=270, downloads=1000, verified=True),

    # ── ClawHub — Testing ─────────────────────────────────────────────────
    _skill("clawhub/jest-modern", name="jest-modern",
        description="Jest with TypeScript, mocking, snapshots, coverage gates.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/jest-modern",
        tags=["javascript", "testing"], stars=620, downloads=3100, verified=True),
    _skill("clawhub/vitest-patterns", name="vitest-patterns",
        description="Vitest: fast Vite-native testing with TypeScript and JSDOM.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/vitest-patterns",
        tags=["javascript", "testing", "vitest"], stars=410, downloads=1800, verified=True),
    _skill("clawhub/playwright-e2e", name="playwright-e2e",
        description="End-to-end testing with Playwright: fixtures, parallel, traces.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/playwright-e2e",
        tags=["testing", "e2e", "playwright"], stars=550, downloads=2400, verified=True),
    _skill("clawhub/cypress-modern", name="cypress-modern",
        description="Cypress component + e2e tests with custom commands.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/cypress-modern",
        tags=["testing", "e2e", "cypress"], stars=330, downloads=1300, verified=True),

    # ── ClawHub — AI/ML ───────────────────────────────────────────────────
    _skill("clawhub/llm-prompts", name="llm-prompts",
        description="Prompt engineering: chain-of-thought, few-shot, structured output.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/llm-prompts",
        tags=["ai", "llm"], stars=1180, downloads=7100, verified=True),
    _skill("clawhub/embeddings-search", name="embeddings-search",
        description="Embedding workflows: chunking, batching, ANN indexes, hybrid search.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/embeddings-search",
        tags=["ai", "embeddings", "search"], stars=520, downloads=2400, verified=True),
    _skill("clawhub/langgraph-recipes", name="langgraph-recipes",
        description="LangGraph state machines: nodes, edges, checkpointing, interrupts.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/langgraph-recipes",
        tags=["ai", "langgraph"], stars=410, downloads=1700, verified=True),
    _skill("clawhub/sklearn-essentials", name="sklearn-essentials",
        description="scikit-learn: pipelines, cross-val, calibration, common pitfalls.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/sklearn-essentials",
        tags=["python", "ml", "sklearn"], stars=390, downloads=1500, verified=True),
    _skill("clawhub/pytorch-modern", name="pytorch-modern",
        description="PyTorch 2.x: torch.compile, AMP, DDP, dataloader patterns.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/pytorch-modern",
        tags=["python", "ml", "pytorch"], stars=460, downloads=2000, verified=True),

    # ── ClawHub — Mobile ──────────────────────────────────────────────────
    _skill("clawhub/react-native-2026", name="react-native-2026",
        description="React Native with the new architecture (Fabric + TurboModules).",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/react-native-2026",
        tags=["mobile", "react"], stars=340, downloads=1400, verified=True),
    _skill("clawhub/flutter-modern", name="flutter-modern",
        description="Flutter with Riverpod state, slivers, performance budgets.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/flutter-modern",
        tags=["mobile", "flutter", "dart"], stars=310, downloads=1200, verified=True),
    _skill("clawhub/swift-modern", name="swift-modern",
        description="Swift 5+ idioms: async/await, actors, structured concurrency.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/swift-modern",
        tags=["mobile", "swift", "ios"], stars=240, downloads=900, verified=True),
    _skill("clawhub/kotlin-coroutines", name="kotlin-coroutines",
        description="Kotlin coroutines and Flow patterns for Android.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/kotlin-coroutines",
        tags=["mobile", "kotlin", "android"], stars=270, downloads=1100, verified=True),

    # ── ClawHub — Security / Review ───────────────────────────────────────
    _skill("clawhub/security-review", name="security-review",
        description="OWASP Top 10 review with concrete code examples per finding.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/security-review",
        tags=["security", "review"], stars=720, downloads=3300, verified=True),
    _skill("clawhub/auth-patterns", name="auth-patterns",
        description="OAuth, OIDC, JWT, session cookies — when to use which, common bugs.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/auth-patterns",
        tags=["security", "auth"], stars=580, downloads=2700, verified=True),
    _skill("clawhub/secrets-handling", name="secrets-handling",
        description="Secrets: env vars, vaults, rotation, never-commit hygiene.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/secrets-handling",
        tags=["security", "secrets"], stars=340, downloads=1400, verified=True),

    # ── ClawHub — Code review / Refactor ──────────────────────────────────
    _skill("clawhub/code-review-pr", name="code-review-pr",
        description="Reviewing PRs: scope, blast radius, risks, asks for change.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/code-review-pr",
        tags=["review", "code"], stars=460, downloads=2000, verified=True),
    _skill("clawhub/refactor-safely", name="refactor-safely",
        description="Refactor without breaking tests: characterisation, parallel change, deprecation.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/refactor-safely",
        tags=["refactor", "code"], stars=410, downloads=1700, verified=True),
    _skill("clawhub/dead-code-removal", name="dead-code-removal",
        description="Spotting and safely deleting dead code (imports, branches, features).",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/dead-code-removal",
        tags=["refactor", "code"], stars=240, downloads=900, verified=True),

    # ── ClawHub — CLI / Scripting ─────────────────────────────────────────
    _skill("clawhub/bash-modern", name="bash-modern",
        description="Robust bash scripts: set -euo, error traps, signal handling.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/bash-modern",
        tags=["bash", "shell", "cli"], stars=390, downloads=1700, verified=True),
    _skill("clawhub/typer-cli", name="typer-cli",
        description="Python CLIs with Typer: subcommands, completion, rich output.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/typer-cli",
        tags=["python", "cli", "typer"], stars=270, downloads=1100, verified=True),
    _skill("clawhub/click-cli", name="click-cli",
        description="Click idioms: option groups, contexts, plugins.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/click-cli",
        tags=["python", "cli", "click"], stars=190, downloads=700, verified=True),
    _skill("clawhub/oclif-modern", name="oclif-modern",
        description="Node CLIs with oclif: plugins, hooks, telemetry.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/oclif-modern",
        tags=["node", "cli"], stars=140, downloads=400, verified=True),

    # ── ClawHub — Go / Rust ───────────────────────────────────────────────
    _skill("clawhub/go-services", name="go-services",
        description="Idiomatic Go services: context, errgroup, http handlers, gorm.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/go-services",
        tags=["go", "backend"], stars=520, downloads=2300, verified=True),
    _skill("clawhub/rust-modern", name="rust-modern",
        description="Rust idioms: lifetimes, ?, async, error patterns with anyhow/thiserror.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/rust-modern",
        tags=["rust", "backend"], stars=580, downloads=2700, verified=True),
    _skill("clawhub/tokio-async", name="tokio-async",
        description="Tokio: tasks, channels, select!, backpressure.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/tokio-async",
        tags=["rust", "async", "tokio"], stars=320, downloads=1300, verified=True),

    # ── ClawHub — Docs / Writing ──────────────────────────────────────────
    _skill("clawhub/release-notes", name="release-notes",
        description="Drafting clear, useful release notes from a diff.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/release-notes",
        tags=["docs", "writing"], stars=380, downloads=1500, verified=True),
    _skill("clawhub/api-docs", name="api-docs",
        description="API reference docs: endpoint, schema, examples, errors.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/api-docs",
        tags=["docs", "api"], stars=300, downloads=1200, verified=True),
    _skill("clawhub/architecture-docs", name="architecture-docs",
        description="ADRs (architecture decision records) + C4 model diagrams.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/architecture-docs",
        tags=["docs", "architecture"], stars=260, downloads=1000, verified=True),

    # ── ClawHub — Performance ─────────────────────────────────────────────
    _skill("clawhub/web-vitals", name="web-vitals",
        description="Improving LCP/INP/CLS: critical CSS, hydration, font loading.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/web-vitals",
        tags=["frontend", "performance"], stars=420, downloads=1800, verified=True),
    _skill("clawhub/node-perf", name="node-perf",
        description="Node perf: event loop, async hooks, V8 flags, clinic.js.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/node-perf",
        tags=["node", "performance"], stars=240, downloads=900, verified=True),
    _skill("clawhub/python-perf", name="python-perf",
        description="Python perf: profiling, asyncio bottlenecks, NumPy vectorisation, Cython.",
        source="clawhub", source_label="ClawHub",
        url="https://clawhub.dev/skills/python-perf",
        tags=["python", "performance"], stars=350, downloads=1500, verified=True),

    # ── Community GitHub (lower stars or unverified) ──────────────────────
    _skill("github/awesome-claude-skills/owasp-security", name="owasp-security-review",
        description="OWASP Top 10 review patterns — community fork.",
        source="community", source_label="GitHub",
        url="https://github.com/example/awesome-claude-skills/owasp-security",
        tags=["security", "review"], stars=88, verified=False),
    _skill("github/awesome-claude-skills/data-cleaning", name="data-cleaning-recipes",
        description="Pandas + Polars recipes for cleaning real-world data.",
        source="community", source_label="GitHub",
        url="https://github.com/example/awesome-claude-skills/data-cleaning",
        tags=["python", "data"], stars=42, verified=False),
    _skill("github/awesome-claude-skills/llm-evals", name="llm-evals",
        description="Patterns for evaluating LLM outputs — judges, rubrics, golden sets.",
        source="community", source_label="GitHub",
        url="https://github.com/example/awesome-claude-skills/llm-evals",
        tags=["ai", "evals"], stars=156, verified=True),
    _skill("github/awesome-claude-skills/sql-injection-review", name="sql-injection-review",
        description="Audit SQL paths for injection — community contribution.",
        source="community", source_label="GitHub",
        url="https://github.com/example/awesome-claude-skills/sql-injection-review",
        tags=["security", "sql"], stars=22, verified=False),
    _skill("github/awesome-claude-skills/docker-compose-review", name="docker-compose-review",
        description="Review docker-compose files for production readiness.",
        source="community", source_label="GitHub",
        url="https://github.com/example/awesome-claude-skills/docker-compose-review",
        tags=["docker", "devops"], stars=64, verified=False),
    _skill("github/awesome-claude-skills/cron-builder", name="cron-builder",
        description="Translate plain English to cron expressions and back.",
        source="community", source_label="GitHub",
        url="https://github.com/example/awesome-claude-skills/cron-builder",
        tags=["cli", "cron"], stars=31, verified=False),
]


CURATED_MCP_SERVERS: list[dict] = [
    # ── Official MCP Registry ─────────────────────────────────────────────
    _mcp("mcp/filesystem", name="Filesystem",
        description="Read/write files on the local disk. Sandboxed to configured roots per agent.",
        source="official", source_label="MCP Registry",
        install={"transport": "npm", "package": "@modelcontextprotocol/server-filesystem"},
        category="filesystem",
        permissions=["files: read/write within configured roots"],
        homepage="https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
        verified=True, installs=28000),
    _mcp("mcp/sqlite", name="SQLite",
        description="Query and inspect SQLite databases.",
        source="official", source_label="MCP Registry",
        install={"transport": "npm", "package": "@modelcontextprotocol/server-sqlite"},
        category="databases",
        permissions=["files: read SQLite file", "process: spawn sqlite"],
        homepage="https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite",
        verified=True, installs=14000),
    _mcp("mcp/postgres", name="Postgres",
        description="Read-only Postgres queries with schema introspection.",
        source="official", source_label="MCP Registry",
        install={"transport": "npm", "package": "@modelcontextprotocol/server-postgres"},
        category="databases",
        permissions=["network: Postgres connection string"],
        homepage="https://github.com/modelcontextprotocol/servers/tree/main/src/postgres",
        verified=True, installs=9800),
    _mcp("mcp/mysql", name="MySQL",
        description="Read-only MySQL queries with schema introspection.",
        source="official", source_label="MCP Registry",
        install={"transport": "npm", "package": "@modelcontextprotocol/server-mysql"},
        category="databases",
        permissions=["network: MySQL connection string"],
        verified=True, installs=4200),
    _mcp("mcp/redis", name="Redis",
        description="Inspect and manage Redis keys, hashes, streams.",
        source="official", source_label="MCP Registry",
        install={"transport": "npm", "package": "@modelcontextprotocol/server-redis"},
        category="databases",
        permissions=["network: Redis URL"],
        verified=True, installs=3100),
    _mcp("mcp/github", name="GitHub",
        description="Browse repos, read files, comment on issues and PRs.",
        source="official", source_label="MCP Registry",
        install={"transport": "npm", "package": "@modelcontextprotocol/server-github"},
        category="dev tools",
        permissions=["network: api.github.com", "tokens: GITHUB_PERSONAL_ACCESS_TOKEN"],
        homepage="https://github.com/modelcontextprotocol/servers/tree/main/src/github",
        verified=True, installs=21000),
    _mcp("mcp/gitlab", name="GitLab",
        description="GitLab repos, issues, MRs.",
        source="official", source_label="MCP Registry",
        install={"transport": "npm", "package": "@modelcontextprotocol/server-gitlab"},
        category="dev tools",
        permissions=["network: gitlab.com", "tokens: GITLAB_TOKEN"],
        verified=True, installs=2200),
    _mcp("mcp/git", name="Git",
        description="Run git commands inside a configured repo.",
        source="official", source_label="MCP Registry",
        install={"transport": "npm", "package": "@modelcontextprotocol/server-git"},
        category="dev tools",
        permissions=["files: read/write inside repo", "process: spawn git"],
        verified=True, installs=6800),
    _mcp("mcp/brave-search", name="Brave Search",
        description="Web + image search via Brave's API.",
        source="official", source_label="MCP Registry",
        install={"transport": "npm", "package": "@modelcontextprotocol/server-brave-search"},
        category="web search",
        permissions=["network: api.search.brave.com", "tokens: BRAVE_API_KEY"],
        verified=True, installs=6700),
    _mcp("mcp/fetch", name="Fetch",
        description="HTTP GET arbitrary URLs and return HTML or JSON.",
        source="official", source_label="MCP Registry",
        install={"transport": "npm", "package": "@modelcontextprotocol/server-fetch"},
        category="web",
        permissions=["network: arbitrary HTTP"],
        verified=True, installs=11000),
    _mcp("mcp/memory", name="Memory",
        description="Persistent knowledge graph the agent can read and write.",
        source="official", source_label="MCP Registry",
        install={"transport": "npm", "package": "@modelcontextprotocol/server-memory"},
        category="memory",
        permissions=["files: ~/.mcp-memory/"],
        verified=True, installs=5500),
    _mcp("mcp/time", name="Time",
        description="Time-zone-aware now/format helpers.",
        source="official", source_label="MCP Registry",
        install={"transport": "npm", "package": "@modelcontextprotocol/server-time"},
        category="utilities",
        permissions=[],
        verified=True, installs=2800),
    _mcp("mcp/everart", name="EverArt",
        description="Image generation via EverArt.",
        source="official", source_label="MCP Registry",
        install={"transport": "npm", "package": "@modelcontextprotocol/server-everart"},
        category="AI/ML",
        permissions=["network: everart.ai", "tokens: EVERART_API_KEY"],
        verified=True, installs=900),

    # ── Smithery ──────────────────────────────────────────────────────────
    _mcp("smithery/exa-search", name="Exa Search",
        description="Neural search engine for technical content.",
        source="smithery", source_label="Smithery",
        install={"transport": "smithery", "package": "exa-mcp"},
        category="web search",
        permissions=["network: exa.ai", "tokens: EXA_API_KEY"],
        homepage="https://smithery.ai/server/exa-search",
        verified=True, installs=3400),
    _mcp("smithery/tavily", name="Tavily",
        description="Research-oriented web search with source citations.",
        source="smithery", source_label="Smithery",
        install={"transport": "smithery", "package": "tavily-mcp"},
        category="web search",
        permissions=["network: tavily.com", "tokens: TAVILY_API_KEY"],
        verified=True, installs=2200),
    _mcp("smithery/perplexity", name="Perplexity",
        description="Perplexity API: search-grounded LLM answers.",
        source="smithery", source_label="Smithery",
        install={"transport": "smithery", "package": "perplexity-mcp"},
        category="web search",
        permissions=["network: perplexity.ai", "tokens: PERPLEXITY_API_KEY"],
        verified=True, installs=1700),
    _mcp("smithery/linear", name="Linear",
        description="Linear issues, projects, comments.",
        source="smithery", source_label="Smithery",
        install={"transport": "smithery", "package": "linear-mcp"},
        category="project management",
        permissions=["network: api.linear.app", "tokens: LINEAR_API_KEY"],
        verified=True, installs=1100),
    _mcp("smithery/notion", name="Notion",
        description="Read and write Notion pages and databases.",
        source="smithery", source_label="Smithery",
        install={"transport": "smithery", "package": "notion-mcp"},
        category="docs",
        permissions=["network: api.notion.com", "tokens: NOTION_TOKEN"],
        verified=True, installs=2900),
    _mcp("smithery/slack", name="Slack",
        description="Post to channels, read DMs, search messages.",
        source="smithery", source_label="Smithery",
        install={"transport": "smithery", "package": "slack-mcp"},
        category="communication",
        permissions=["network: slack.com", "tokens: SLACK_BOT_TOKEN"],
        verified=True, installs=1800),
    _mcp("smithery/discord", name="Discord",
        description="Post to channels, read DMs.",
        source="smithery", source_label="Smithery",
        install={"transport": "smithery", "package": "discord-mcp"},
        category="communication",
        permissions=["network: discord.com", "tokens: DISCORD_BOT_TOKEN"],
        verified=False, installs=520),
    _mcp("smithery/gmail", name="Gmail",
        description="Search and read Gmail; send drafts.",
        source="smithery", source_label="Smithery",
        install={"transport": "smithery", "package": "gmail-mcp"},
        category="communication",
        permissions=["network: gmail.googleapis.com", "tokens: OAuth"],
        verified=True, installs=830),
    _mcp("smithery/calendar", name="Google Calendar",
        description="Read events and create new entries.",
        source="smithery", source_label="Smithery",
        install={"transport": "smithery", "package": "gcal-mcp"},
        category="productivity",
        permissions=["network: googleapis.com", "tokens: OAuth"],
        verified=True, installs=620),
    _mcp("smithery/airtable", name="Airtable",
        description="Read and write Airtable records.",
        source="smithery", source_label="Smithery",
        install={"transport": "smithery", "package": "airtable-mcp"},
        category="databases",
        permissions=["network: api.airtable.com", "tokens: AIRTABLE_TOKEN"],
        verified=True, installs=540),

    # ── awesome-mcp ───────────────────────────────────────────────────────
    _mcp("awesome/comfyui", name="ComfyUI",
        description="Generate images via a local ComfyUI workflow.",
        source="awesome", source_label="awesome-mcp",
        install={"transport": "npm", "package": "mcp-comfyui"},
        category="AI/ML",
        permissions=["network: localhost ComfyUI", "files: write generated images"],
        homepage="https://github.com/punkpeye/awesome-mcp-servers#comfyui",
        verified=False, installs=410),
    _mcp("awesome/stable-diffusion", name="Stable Diffusion",
        description="Local Stable Diffusion via a wrapper around AUTOMATIC1111.",
        source="awesome", source_label="awesome-mcp",
        install={"transport": "pip", "package": "mcp-sd"},
        category="AI/ML",
        permissions=["network: localhost SD WebUI", "files: write generated images"],
        verified=False, installs=330),
    _mcp("awesome/piper-tts", name="Piper TTS",
        description="Local text-to-speech via Piper (offline).",
        source="awesome", source_label="awesome-mcp",
        install={"transport": "pip", "package": "mcp-piper"},
        category="AI/ML",
        permissions=["files: write audio output", "process: spawn piper"],
        verified=False, installs=180),
    _mcp("awesome/coqui-tts", name="Coqui TTS",
        description="Coqui TTS — higher quality, GPU friendly.",
        source="awesome", source_label="awesome-mcp",
        install={"transport": "pip", "package": "mcp-coqui"},
        category="AI/ML",
        permissions=["files: write audio output", "process: spawn coqui"],
        verified=False, installs=140),
    _mcp("awesome/whisper-stt", name="Whisper STT",
        description="Speech-to-text via OpenAI Whisper (local).",
        source="awesome", source_label="awesome-mcp",
        install={"transport": "pip", "package": "mcp-whisper"},
        category="AI/ML",
        permissions=["files: read audio input", "process: spawn whisper"],
        verified=False, installs=260),
    _mcp("awesome/playwright-mcp", name="Playwright",
        description="Drive a real browser to scrape, screenshot, or automate.",
        source="awesome", source_label="awesome-mcp",
        install={"transport": "npm", "package": "mcp-playwright"},
        category="web",
        permissions=["process: spawn chromium", "network: arbitrary"],
        verified=False, installs=720),
    _mcp("awesome/puppeteer-mcp", name="Puppeteer",
        description="Headless Chrome control — DOM, network mocking, PDF.",
        source="awesome", source_label="awesome-mcp",
        install={"transport": "npm", "package": "mcp-puppeteer"},
        category="web",
        permissions=["process: spawn chromium", "network: arbitrary"],
        verified=False, installs=540),
    _mcp("awesome/aws-mcp", name="AWS",
        description="Read AWS resources (S3, EC2, RDS, Lambda) via boto.",
        source="awesome", source_label="awesome-mcp",
        install={"transport": "pip", "package": "mcp-aws"},
        category="cloud",
        permissions=["network: AWS regional endpoints", "tokens: AWS credentials"],
        verified=False, installs=380),
]
